export const GET_INCIDENT_DETAILS = 'https://kroger.service-now.com/api/now/table/incident?sysparm_display_value=true&sysparm_query=number='

export const INC6070530 = {
    "result": [
        {
            "promoted_by": "",
            "u_refused_troubleshooting": "false",
            "parent": "",
            "u_vendor_name": "",
            "caused_by": "",
            "watch_list": "",
            "u_alternate_phone": "4799700016",
            "upon_reject": "Cancel all future Tasks",
            "sys_updated_on": "2024-06-04 12:33:21",
            "u_mim_ttr": "",
            "u_secure_type": "",
            "origin_table": "",
            "u_display_secure_fields": "true",
            "approval_history": "",
            "u_information_provider_gln": "",
            "skills": "",
            "u_reported_by": "",
            "number": "INC6070530",
            "proposed_by": "",
            "u_meeting_bitly": "",
            "u_teams_general_use": {
                "display_value": "User Training - Basic Functionality Issue",
                "link": "https://kroger.service-now.com/api/now/table/u_generic_choice_table/28d30362c3ac1110993c251ce001313b"
            },
            "lessons_learned": null,
            "u_manitou_account_number": "",
            "state": "In Progress",
            "u_mim_ttd": "",
            "sys_created_by": "svc6126five9p@kroger.com",
            "knowledge": "false",
            "order": "",
            "u_resolved": "false",
            "cmdb_ci": {
                "display_value": "SAT - APP - FRESHPRODUCTION",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci/d711650c1b2941d0a08d6394604bcb8e"
            },
            "cmdb_ci_business_app": "",
            "contract": "",
            "impact": "2 - Site Impact/Department",
            "active": "true",
            "work_notes_list": "",
            "u_preferred_contact_number": "870-761-6799",
            "priority": "3 - Moderate",
            "sys_domain_path": "/",
            "u_missing_vendor": "false",
            "business_duration": "47 Minutes",
            "group_list": "",
            "scr_vendor_point_of_contact": "",
            "u_awaiting_caller_from": "",
            "u_count": "",
            "major_incident_state": null,
            "needs_attention": "false",
            "universal_request": "",
            "short_description": "Probes are not capturing temperature data ",
            "correlation_display": "",
            "work_start": "",
            "u_rx_3rd_party": "",
            "u_ebonding_vendor": null,
            "additional_assignee_list": "",
            "u_pir_owner": "",
            "scr_vendor": "",
            "notify": "Do Not Notify",
            "service_offering": "",
            "sys_class_name": "Incident",
            "closed_by": "",
            "follow_up": "",
            "parent_incident": "",
            "u_major_incident_type": null,
            "u_subcategory_2": null,
            "reopened_by": {
                "display_value": "Alejandro Alvarado",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/aa40d3131b7b2c183faa2f0b234bcb53"
            },
            "u_subcategory_1": null,
            "u_missing_vendor_name": "",
            "u_service_bypass": "false",
            "reassignment_count": "3",
            "u_callback_url": "",
            "assigned_to": {
                "display_value": "Kshitij Raj",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/342938371ba3a4903faa2f0b234bcb33"
            },
            "u_change_related": "false",
            "u_mitigation": "",
            "sla_due": "UNKNOWN",
            "u_organization_number": "",
            "scr_vendor_closed_at": "",
            "u_cause_code": null,
            "escalation": "Normal",
            "upon_approval": "Proceed to Next Task",
            "scr_vendor_opened_at": "",
            "correlation_id": "",
            "timeline": null,
            "u_compliance_type": null,
            "u_ci_name": "",
            "u_vendor_ticket_number": "",
            "u_forwarded_count": "0",
            "made_sla": "true",
            "promoted_on": "",
            "child_incidents": "0",
            "u_meeting_url": "",
            "u_missing_ci": "false",
            "hold_reason": "",
            "task_effective_number": "INC6070530",
            "u_location_note": "",
            "resolved_by": "",
            "u_currency_1": "$0.00",
            "sys_updated_by": "sneha.mishra@kroger.com",
            "opened_by": {
                "display_value": "Five9 API",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/6705a3f947bd5110c43da87a836d4312"
            },
            "user_input": "",
            "sys_created_on": "2024-05-31 11:17:23",
            "sys_domain": {
                "display_value": "global",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/global"
            },
            "proposed_on": "",
            "route_reason": "",
            "u_alternate_location": "",
            "u_confidential_type": "No, This incident does not contain any confidential data - User Standard",
            "calendar_stc": "1 Hour 30 Minutes",
            "u_company_name": "",
            "closed_at": "",
            "u_contributing_factors": "",
            "u_maintenance_issue_number": "",
            "u_patient_waiting": "false",
            "u_service_call_avoid": "false",
            "scr_vendor_resolved_at": "",
            "u_alternate_contact": "",
            "business_service": {
                "display_value": "STORE ORDERING",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci_service/5c98699d1ba54554a08d6394604bcba3"
            },
            "u_rpt_automatedmanual_test": "false",
            "business_impact": "",
            "rfc": "",
            "time_worked": "",
            "expected_start": "",
            "u_email_address": "",
            "u_secondary_company_name": "",
            "u_vendor_related": "false",
            "opened_at": "2024-05-31 11:17:23",
            "u_secured_by": "",
            "work_end": "",
            "caller_id": {
                "display_value": "Hera Milton",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/2076d0451b99c150a08d6394604bcb08"
            },
            "reopened_time": "2024-05-31 16:38:57",
            "resolved_at": "",
            "u_kgr_euids": "",
            "subcategory": null,
            "work_notes": "2024-05-31 16:49:03 - Kyle Roders (Work notes)\nReviewed\r\nSite states that they're still not seeing updates to the temp monitoring siteshttps://templog.kroger.com/home\r\nEscalating\n\n2024-05-31 16:40:11 - Alejandro Alvarado (Work notes)\n- assistant manager called back states issue continues.\r\n\r\n- posting for review to re-escalate to APP-SAT-InStockSupport\n\n2024-05-31 11:53:52 - Brennan Gilmore (Work notes)\nIncoming Call from customer for 38 Minutes\n\n2024-05-31 11:43:26 - Brennan Gilmore (Work notes)\nZebras are connecting to the \r\nand are able to do the temps \r\n\r\nnot showing on the log application\r\n\r\njust started the new temp probes yesterday \r\nnone of the temp logs had sent the data to the cool log site \r\n\r\nthe store is temping and going through the workflow correctly \r\ndoes say that they submitted the temps too but is not showing on the temperature monitoring website since 5/28/24\r\n\r\nI checked myself on that website and does look like they are missing for the past few days \r\nhttps://templog.kroger.com/home\r\n\r\ngoing to go ahead and send ticket over to app-sat-instocksupport to see if they could take a look \r\nnot seeing any network issues in that area and probes are connecting to the zebras without issue \r\n\r\n[code]<a title=\"Zigbee Digital Thermometer Probe Overview (older model)\" href='kb_view.do?sys_kb_id=8ef29d8947c68214ed0faf4a216d434f' >KB0014664 : Zigbee Digital Thermometer Probe Overview (older model)</a>[/code]\r\n[code]<a title=\"Fresh Production – Deli Hot &amp; Chilled Chicken Workflow\" href='kb_view.do?sys_kb_id=fc134c2047a8c65086251e27e26d434c' >KB0032891 : Fresh Production – Deli Hot &amp; Chilled Chicken Workflow</a>[/code]\r\n[code]<a title=\"Fresh Production: User reports they can't temp an item in their Cool Log.\" href='kb_view.do?sys_kb_id=acba782e47dc0a1cf00380fc416d4337' >KB0020335 : Fresh Production: User reports they can't temp an item in their Cool Log.</a>[/code]\n\n2024-05-31 11:23:41 - Thomas Oravetz (Work notes)\nIncoming Call from customer for 7 Minutes\n\n",
            "close_code": null,
            "assignment_group": {
                "display_value": "APP-SAT-InStockSupport",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/09e57dbf1b1dc1181c905425604bcb0b"
            },
            "u_duns_number": "",
            "u_pir_date": "",
            "business_stc": "2,855",
            "cause": "",
            "description": "",
            "origin_id": "",
            "u_faliure_code": "#ProductTeamFollowUp",
            "calendar_duration": "1 Hour 30 Minutes",
            "close_notes": "",
            "sys_id": "ab961085c3aa4a14206a92977d01310e",
            "contact_type": "Phone",
            "incident_state": "In Progress",
            "urgency": "2 - Today",
            "problem_id": "",
            "u_kgr_division": {
                "display_value": "025-Delta Operating Division",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/80b83f6c1b41491025c54005bd4bcb6e"
            },
            "company": "",
            "u_current_status": "",
            "activity_due": "UNKNOWN",
            "u_ritm_number": "",
            "action_status": "",
            "severity": "3 - Low",
            "overview": null,
            "comments": "",
            "u_impact_start": "",
            "approval": "Not Yet Requested",
            "due_date": "",
            "sys_mod_count": "14",
            "reopen_count": "1",
            "sys_tags": "",
            "scr_vendor_ticket": "",
            "u_job_name": "",
            "location": {
                "display_value": "00409-025-Kroger Marketplace",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/683ec9951b89c51025c54005bd4bcb9c"
            },
            "category": "KSC",
            "u_impact_end": "",
            "u_vendor_ticket_status": null,
            "u_impact_detected": ""
        }
    ]
}

export const INC6028019 = {
    "result": [
        {
            "promoted_by": "",
            "u_refused_troubleshooting": "false",
            "parent": "",
            "u_vendor_name": "",
            "caused_by": "",
            "watch_list": "",
            "u_alternate_phone": "",
            "upon_reject": "Cancel all future Tasks",
            "sys_updated_on": "2024-06-04 11:35:38",
            "u_mim_ttr": "",
            "u_secure_type": "",
            "origin_table": "",
            "u_display_secure_fields": "false",
            "approval_history": "",
            "u_information_provider_gln": "",
            "skills": "",
            "u_reported_by": "",
            "number": "INC6028019",
            "proposed_by": "",
            "u_meeting_bitly": "",
            "u_teams_general_use": "",
            "lessons_learned": null,
            "u_manitou_account_number": "",
            "state": "Assigned",
            "u_mim_ttd": "",
            "sys_created_by": "s5068SvcNowAPIUserP@kroger.com",
            "knowledge": "false",
            "order": "",
            "u_resolved": "false",
            "cmdb_ci": {
                "display_value": "SAT-MyDay",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci/1636b24e1b3505501c905425604bcb6e"
            },
            "cmdb_ci_business_app": "",
            "contract": "",
            "impact": "3 - Several Users",
            "active": "true",
            "work_notes_list": "",
            "u_preferred_contact_number": "937-390-2390",
            "priority": "4 - Low",
            "sys_domain_path": "/",
            "u_missing_vendor": "false",
            "business_duration": "",
            "group_list": "",
            "scr_vendor_point_of_contact": "",
            "u_awaiting_caller_from": "",
            "u_count": "",
            "major_incident_state": null,
            "needs_attention": "false",
            "universal_request": "",
            "short_description": "Description: not really an issue more of a suggestion. Can you make it to where you can't complete trucks until everything has been scanned. I keep accidentally",
            "correlation_display": "",
            "work_start": "",
            "u_rx_3rd_party": "",
            "u_ebonding_vendor": null,
            "additional_assignee_list": "",
            "u_pir_owner": "",
            "scr_vendor": "",
            "notify": "Do Not Notify",
            "service_offering": "",
            "sys_class_name": "Incident",
            "closed_by": "",
            "follow_up": "",
            "parent_incident": "",
            "u_major_incident_type": null,
            "u_subcategory_2": null,
            "reopened_by": "",
            "u_subcategory_1": "Back Office",
            "u_missing_vendor_name": "",
            "u_service_bypass": "false",
            "reassignment_count": "1",
            "u_callback_url": "",
            "assigned_to": {
                "display_value": "Vinay Kumar Pammi",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/f2fc1ac61b1d0dd0a08d6394604bcba5"
            },
            "u_change_related": "false",
            "u_mitigation": "",
            "sla_due": "UNKNOWN",
            "u_organization_number": "",
            "scr_vendor_closed_at": "",
            "u_cause_code": null,
            "escalation": "Normal",
            "upon_approval": "Proceed to Next Task",
            "scr_vendor_opened_at": "",
            "correlation_id": "",
            "timeline": null,
            "u_compliance_type": null,
            "u_ci_name": "",
            "u_vendor_ticket_number": "",
            "u_forwarded_count": "0",
            "made_sla": "true",
            "promoted_on": "",
            "child_incidents": "0",
            "u_meeting_url": "",
            "u_missing_ci": "false",
            "hold_reason": "",
            "task_effective_number": "INC6028019",
            "u_location_note": "",
            "resolved_by": "",
            "u_currency_1": "$0.00",
            "sys_updated_by": "vinaykumar.pammi@kroger.com",
            "opened_by": {
                "display_value": "SpsConfig Server App API",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/0afafb201b7e0110684965f3604bcb5f"
            },
            "user_input": "",
            "sys_created_on": "2024-05-27 01:47:30",
            "sys_domain": {
                "display_value": "global",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/global"
            },
            "proposed_on": "",
            "route_reason": "",
            "u_alternate_location": "",
            "u_confidential_type": "No, This incident does not contain any confidential data - User Standard",
            "calendar_stc": "",
            "u_company_name": "",
            "closed_at": "",
            "u_contributing_factors": "",
            "u_maintenance_issue_number": "",
            "u_patient_waiting": "false",
            "u_service_call_avoid": "false",
            "scr_vendor_resolved_at": "",
            "u_alternate_contact": "",
            "business_service": {
                "display_value": "STORE ORDERING",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci_service/5c98699d1ba54554a08d6394604bcba3"
            },
            "u_rpt_automatedmanual_test": "true",
            "business_impact": "",
            "rfc": "",
            "time_worked": "",
            "expected_start": "",
            "u_email_address": "",
            "u_secondary_company_name": "",
            "u_vendor_related": "false",
            "opened_at": "2024-05-27 01:47:30",
            "u_secured_by": "",
            "work_end": "",
            "caller_id": {
                "display_value": "Andrew Chapman",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/fb89d4851bd9c150a08d6394604bcb9e"
            },
            "reopened_time": "",
            "resolved_at": "",
            "u_kgr_euids": "",
            "subcategory": "Store Support",
            "work_notes": "2024-05-29 14:11:54 - Ben Butterfield (Work notes)\nSending to IS Support first, please forward to proper team if needed.\r\n[code]<a title=\"Instock: Unable to view open orders/ Unable to see deliveries\" href='kb_view.do?sys_kb_id=71e561a4c3e58e102fc73bca050131b8' >KB0015421 : Instock: Unable to view open orders/ Unable to see deliveries</a>[/code]\n\n",
            "close_code": "Resolved by Analyst",
            "assignment_group": {
                "display_value": "APP-SAT-InStockSupport",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/09e57dbf1b1dc1181c905425604bcb0b"
            },
            "u_duns_number": "",
            "u_pir_date": "",
            "business_stc": "",
            "cause": "",
            "description": "Description: not really an issue more of a suggestion. Can you make it to where you can't complete trucks until everything has been scanned. I keep accidentally pressing complete truck when looking for tags.\nApplication/Capability: Receive Truck\nScreen/Area: scanning in trucks\nOccurred: Just Now\n\n\nLast Scanned: No Scanned UPCs\nReport Issue Version: 4.9.0\nMac Address: 78:B8:D6:04:27:F4\nModel: TC52         \nNetwork Info: SSID: \"InS+0cK\", Access Point: b8:50:01:05:6d:64, WiFi Signal Strength: -66, IP Address: -64.-88.-25.42, Scan Results: \nAP b8:50:01:03:d3:38 : WSS -48\nAP b8:50:01:04:1a:13 : WSS -49\nAP b8:50:01:03:d3:30 : WSS -49\nAP b8:50:01:03:d3:31 : WSS -49\nAP b8:50:01:03:d3:33 : WSS -49\nEnvironment: PROD\nLinked Key: d8db06d8-356d-4c11-9bea-f9b7b7ef9e7e",
            "origin_id": "",
            "u_faliure_code": "",
            "calendar_duration": "",
            "close_notes": "",
            "sys_id": "1cdda9a397de8a183593331f2153af7c",
            "contact_type": "Event",
            "incident_state": "Assigned",
            "urgency": "4 - Within a week",
            "problem_id": "",
            "u_kgr_division": {
                "display_value": "014-Cincinnati Operating Division",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/eda8b7e4db818910796aab0b1396197e"
            },
            "company": "",
            "u_current_status": "",
            "activity_due": "UNKNOWN",
            "u_ritm_number": "",
            "action_status": "",
            "severity": "3 - Low",
            "overview": null,
            "comments": "",
            "u_impact_start": "",
            "approval": "Not Yet Requested",
            "due_date": "",
            "sys_mod_count": "6",
            "reopen_count": "0",
            "sys_tags": "",
            "scr_vendor_ticket": "",
            "u_job_name": "",
            "location": {
                "display_value": "00741-014-Kroger",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/84447c15dbc98510796aab0b13961983"
            },
            "category": "KSC",
            "u_impact_end": "",
            "u_vendor_ticket_status": null,
            "u_impact_detected": ""
        }
    ]
}

export const INC6050882 = {
    "result": [
        {
            "promoted_by": "",
            "u_refused_troubleshooting": "false",
            "parent": "",
            "u_vendor_name": "",
            "caused_by": "",
            "watch_list": "",
            "u_alternate_phone": "",
            "upon_reject": "Cancel all future Tasks",
            "sys_updated_on": "2024-06-04 06:41:43",
            "u_mim_ttr": "",
            "u_secure_type": "",
            "origin_table": "",
            "u_display_secure_fields": "false",
            "approval_history": "",
            "u_information_provider_gln": "",
            "skills": "",
            "u_reported_by": "",
            "number": "INC6050882",
            "proposed_by": "",
            "u_meeting_bitly": "",
            "u_teams_general_use": "",
            "lessons_learned": null,
            "u_manitou_account_number": "",
            "state": "Assigned",
            "u_mim_ttd": "",
            "sys_created_by": "s5068SvcNowAPIUserP@kroger.com",
            "knowledge": "false",
            "order": "",
            "u_resolved": "false",
            "cmdb_ci": {
                "display_value": "SAT-Storewalk",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci/75f57a4e1b3505501c905425604bcb46"
            },
            "cmdb_ci_business_app": "",
            "contract": "",
            "impact": "2 - Site Impact/Department",
            "active": "true",
            "work_notes_list": "",
            "u_preferred_contact_number": "928-445-3010",
            "priority": "3 - Moderate",
            "sys_domain_path": "/",
            "u_missing_vendor": "false",
            "business_duration": "",
            "group_list": "",
            "scr_vendor_point_of_contact": "",
            "u_awaiting_caller_from": "",
            "u_count": "",
            "major_incident_state": null,
            "needs_attention": "false",
            "universal_request": "",
            "short_description": "Capability: Tasks   Issue Type: OtherDescription: all associates are not showing up for sweeps when we schedule them for utilityStore Walk Version: 6.1.1Mac",
            "correlation_display": "",
            "work_start": "",
            "u_rx_3rd_party": "",
            "u_ebonding_vendor": null,
            "additional_assignee_list": "",
            "u_pir_owner": "",
            "scr_vendor": "",
            "notify": "Do Not Notify",
            "service_offering": "",
            "sys_class_name": "Incident",
            "closed_by": "",
            "follow_up": "",
            "parent_incident": "",
            "u_major_incident_type": null,
            "u_subcategory_2": null,
            "reopened_by": "",
            "u_subcategory_1": "Back Office",
            "u_missing_vendor_name": "",
            "u_service_bypass": "false",
            "reassignment_count": "1",
            "u_callback_url": "",
            "assigned_to": {
                "display_value": "Anoop Sahani",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/9b692f8b93a84e50c396f3ed1dba10c1"
            },
            "u_change_related": "false",
            "u_mitigation": "",
            "sla_due": "UNKNOWN",
            "u_organization_number": "",
            "scr_vendor_closed_at": "",
            "u_cause_code": null,
            "escalation": "Normal",
            "upon_approval": "Proceed to Next Task",
            "scr_vendor_opened_at": "",
            "correlation_id": "",
            "timeline": null,
            "u_compliance_type": null,
            "u_ci_name": "",
            "u_vendor_ticket_number": "",
            "u_forwarded_count": "0",
            "made_sla": "true",
            "promoted_on": "",
            "child_incidents": "0",
            "u_meeting_url": "",
            "u_missing_ci": "false",
            "hold_reason": "",
            "task_effective_number": "INC6050882",
            "u_location_note": "",
            "resolved_by": "",
            "u_currency_1": "$0.00",
            "sys_updated_by": "anoop.sahani@kroger.com",
            "opened_by": {
                "display_value": "SpsConfig Server App API",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/0afafb201b7e0110684965f3604bcb5f"
            },
            "user_input": "",
            "sys_created_on": "2024-05-29 14:02:28",
            "sys_domain": {
                "display_value": "global",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/global"
            },
            "proposed_on": "",
            "route_reason": "",
            "u_alternate_location": "",
            "u_confidential_type": "No, This incident does not contain any confidential data - User Standard",
            "calendar_stc": "",
            "u_company_name": "",
            "closed_at": "",
            "u_contributing_factors": "",
            "u_maintenance_issue_number": "",
            "u_patient_waiting": "false",
            "u_service_call_avoid": "false",
            "scr_vendor_resolved_at": "",
            "u_alternate_contact": "",
            "business_service": {
                "display_value": "STORE ORDERING",
                "link": "https://kroger.service-now.com/api/now/table/cmdb_ci_service/5c98699d1ba54554a08d6394604bcba3"
            },
            "u_rpt_automatedmanual_test": "true",
            "business_impact": "",
            "rfc": "",
            "time_worked": "",
            "expected_start": "",
            "u_email_address": "",
            "u_secondary_company_name": "",
            "u_vendor_related": "false",
            "opened_at": "2024-05-29 14:02:28",
            "u_secured_by": "",
            "work_end": "",
            "caller_id": {
                "display_value": "Susan Smith",
                "link": "https://kroger.service-now.com/api/now/table/sys_user/9c6d97b81b594150a08d6394604bcb21"
            },
            "reopened_time": "",
            "resolved_at": "",
            "u_kgr_euids": "",
            "subcategory": "Store Support",
            "work_notes": "2024-06-02 08:17:59 - Brad Turner (Work notes)\n[code]<a title=\"StoreWalk Application\" href='kb_view.do?sys_kb_id=80ff4090c3ed4a102fc73bca0501318e' >KB0025519 : StoreWalk Application</a>[/code]\r\nIssue not listed in the docs or the known issues list.\r\nSending to APP-SAT-ISS for review.\n\n",
            "close_code": "Resolved by Analyst",
            "assignment_group": {
                "display_value": "APP-SAT-InStockSupport",
                "link": "https://kroger.service-now.com/api/now/table/sys_user_group/09e57dbf1b1dc1181c905425604bcb0b"
            },
            "u_duns_number": "",
            "u_pir_date": "",
            "business_stc": "",
            "cause": "",
            "description": "Capability: Tasks   \nIssue Type: Other\nDescription: all associates are not showing up for sweeps when we schedule them for utility\nStore Walk Version: 6.1.1\nMac Address: 78:B8:D6:DC:D0:87\nModel: TC52          \nNetwork Info: \nEnvironment: PROD",
            "origin_id": "",
            "u_faliure_code": "",
            "calendar_duration": "",
            "close_notes": "",
            "sys_id": "ce39e6d093ee0e1804267f9efaba10ee",
            "contact_type": "Event",
            "incident_state": "Assigned",
            "urgency": "2 - Today",
            "problem_id": "",
            "u_kgr_division": {
                "display_value": "660-Frys Operating Division",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/171af364dbc18910796aab0b1396195c"
            },
            "company": "",
            "u_current_status": "",
            "activity_due": "UNKNOWN",
            "u_ritm_number": "",
            "action_status": "",
            "severity": "3 - Low",
            "overview": null,
            "comments": "",
            "u_impact_start": "",
            "approval": "Not Yet Requested",
            "due_date": "",
            "sys_mod_count": "7",
            "reopen_count": "0",
            "sys_tags": "",
            "scr_vendor_ticket": "",
            "u_job_name": "",
            "location": {
                "display_value": "00063-660-Fry's Food And Drug",
                "link": "https://kroger.service-now.com/api/now/table/cmn_location/3b923fd9dbc58910796aab0b139619f6"
            },
            "category": "KSC",
            "u_impact_end": "",
            "u_vendor_ticket_status": null,
            "u_impact_detected": ""
        }
    ]
}